### ISSUE TITLE
Colour scales calculated in D3

### ISSUE THREAD

**Issue by simonwinter** [dragonfly-science/bailiwick-ui#23]
Some maps (e.g. http://webrear.mbie.govt.nz/theme/population-estimates/map/timeseries/2018/new-zealand?left-transform=indexed&right-transform=absolute) show data in different units to the raw value - i.e. percentage, dollar amounts etc.

Currently, we are not always showing this transformed label.

**Comment by finlay** [comment]
Move the scales into D3

**Comment by simonwinter** [comment]
Almost there! We need to change the array of scale data being passed to the js into min & max values & we're away!

**Comment by finlay** [comment]
This is done
