### ISSUE TITLE
Rubbish data!

### ISSUE THREAD

**Issue by finlay** [dragonfly-science/bailiwick-ui#31]
http://bailiwick-ui.dragonfly-science.gorbachev.io/theme/household-income-mean/map/barchart/2016/auckland--orakei/?areatype=ward&right-transform=indexed&mapzoom=1

**Comment by simonwinter** [comment]
We're still getting these kind of values in some of the json files:

```json
{
    "headline": "$NA",
    "local": "...",
    "national": "  NA",
    "indexDisp": "    NA"
}
```

Specifically, these files are generating the error currently:

* gdp-by-industry.json
* international-visitor-nights.json
* international-visits.json
* tourism-spend.json

**Comment by simonwinter** [comment]
Same issue happens in the scale in the json files - you get:

```json
{},
{
    "year": 2009,
    "feature": "africa-and-middle-east",
    "minval": 0.0055,
    "maxval": 269.2316
},
...
```
