### ISSUE TITLE
Add no-data case back in

### ISSUE THREAD

**Issue by finlay** [dragonfly-science/bailiwick-ui#36]

**Comment by finlay** [comment]
We can get here via lots of directions.

**Comment by simonwinter** [comment]
The "No data" labels have been added in. I was originally adding the stripe colour to the map whenever we have a colour coming back as #FFFFFF - i.e:

```hs
setAttr (sel <> " > path") "fill" colour
    (if colour = "#FFFFFF" then "url(#lightstripe)" else colour)
```

I'm not sure if this logic is valid - i.e. are there circumstances when a region of the map should be white?

**Comment by finlay** [comment]
This is okay for now. If is white, it means no-data.
