### ISSUE TITLE
indicator tree

### ISSUE THREAD

**Issue by finlay** [dragonfly-science/bailiwick-ui#7]

**Comment by simonwinter** [comment]
No more progress can be made until #18 is resolved.

**Comment by simonwinter** [comment]
Currently, there are no indicatorNumbers being passed to the treemap.

We get the following error output:

```
getIndicatorDataResponse failure: Error in $.numbers: key "areaid" not present
```

**Comment by simonwinter** [comment]
The `tourism-spend.json` file is still giving us:

```
{
    "headline": "$NA",
    "local": "...",
    "national": "  NA",
    "indexDisp": "    NA"
}
```

**Comment by finlay** [comment]
Known problem, Tourism Spend is a special case.
